name: Test with Maven

jobs:
  test-maven:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: clean
        run: mvn clean install

      - name: test
        run: mvn test